# Spring
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/personalbudget
    username: postgres
    password: 12345
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# Tomcat
server:
  error:
    include-exception: true
    include-message: always
    include-stacktrace: always
